version: "3.9"

services:

  #########################################
  # PostgreSQL
  #########################################
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  #########################################
  # NATS
  #########################################
  nats:
    image: nats:2.10
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - backend

  #########################################
  # Redis
  #########################################
  redis-rinha:
    image: redis:7-alpine
    container_name: redis-rinha
    ports:
      - "6379:6379"
    networks:
      - backend

  #########################################
  # Processadores de pagamento externos
  #########################################
  default-processor:
    image: zanfranceschi/payment-processor:amd64-20250707101540
    container_name: default-processor
    networks:
      - payment-processor

  fallback-processor:
    image: zanfranceschi/payment-processor:amd64-20250707101540
    container_name: fallback-processor
    networks:
      - payment-processor

  #########################################
  # NGINX Load Balancer
  #########################################
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    networks:
      - backend

  #########################################
  # API - Instância 1
  #########################################
  api01:
    image: rinha-api
    container_name: api01
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=rinha;Username=rinha;Password=rinha"
      Nats__Url: "nats://nats:4222"
    depends_on:
      - postgres
      - nats
    networks:
      - backend
      - payment-processor
    expose:
      - "8080"

  #########################################
  # API - Instância 2
  #########################################
  api02:
    image: rinha-api
    container_name: api02
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=rinha;Username=rinha;Password=rinha"
      Nats__Url: "nats://nats:4222"
    depends_on:
      - postgres
      - nats
    networks:
      - backend
      - payment-processor
    expose:
      - "8080"

  #########################################
  # Worker de Pagamento
  #########################################
  payment-worker:
    image: rinha-worker
    container_name: payment-worker
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=rinha;Username=rinha;Password=rinha"
      Nats__Url: "nats://nats:4222"
    depends_on:
      - postgres
      - nats
      - redis-rinha
      - default-processor
      - fallback-processor
    networks:
      - backend
      - payment-processor

volumes:
  pg_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
