version: "3.9"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

services:
  # API - Instância 1
  api01:
    image: payment-api
    depends_on:
      - db
      - redis
      - nats
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Postgres=Host=db;Port=5432;Username=admin;Password=rinha@123;Database=PaymentDB
      - DOTNET_ENVIRONMENT=Production
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "52MB"

  # API - Instância 2
  api02:
    image: payment-api
    depends_on:
      - db
      - redis
      - nats
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Postgres=Host=db;Port=5432;Username=admin;Password=rinha@123;Database=PaymentDB
      - DOTNET_ENVIRONMENT=Production
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "52MB"

  # Worker responsável por processar os pagamentos
  payment-worker:
    image: payment-worker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      nats:
        condition: service_started
    environment:
      - DOTNET_ENVIRONMENT=Production
      - ConnectionStrings__Postgres=Host=db;Port=5432;Username=admin;Password=rinha@123;Database=PaymentDB;MaxPoolSize=300
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "60MB"

  # Banco de dados PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: PaymentDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rinha@123
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d PaymentDB"]
      interval: 3s
      timeout: 2s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "150MB"

  # Redis para cache
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "30MB"

  # NATS para mensageria entre serviços
  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "30MB"

  # NGINX para balanceamento de carga entre api01 e api02
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "30MB"
